name: SateSpawnerAPI
version: '1.4.0'
main: org.satellite.dev.progiple.satespawnerapi.SateSpawnerAPI
api-version: '1.16'
authors:
  - NovaSparkle
  - ProGiple

depend:
  - LunaSpring
  - NBTAPI

commands:
  satespawnerapi:
    aliases:
      - sspapi
      - spawnerapi
      - spawnersapi
      - satespawner

permissions:
  ssapi.reload:
    default: op